title: "GG Maths"
description: "Expert online maths tutoring for ages 7–18. Boost confidence and exam results with tailored 1:1 support and proven strategies."
url: "https://gg1982.github.io"
baseurl: "/ggmaths-2025" # Only needed if you're using a subfolder

author:
  name: "Giuliano"
  email: "info@ggmaths.co.uk"

lang: "en-GB"

social:
  name: "GG Maths"
  links:
    - https://www.youtube.com/@ggmaths
    - https://www.instagram.com/ggmaths

logo: "/assets/images/logo.png"
image: "/assets/images/social-share-preview.jpg"

# Pagination Settings
paginate: 6              # Number of posts to show per page
paginate_path: "/blog/page:num/" # URL structure for paginated pages

plugins:
  - jekyll-paginate

